#!/usr/bin/env python3
"""Trellis mockup approval.

A mockup is only useful as a gate if approval cannot drift from what was approved. The obvious
implementation — write an approval file, check it exists — is forgeable: get approval, then edit the
mockup, and the check still passes.

So approval records a hash of everything that determines what the reviewer actually saw: the mockup
files, and the design tokens they were rendered against. Change any of it and approval is void.

Usage:
  mockup.py approve <spec-id>   record approval for docs/mockups/<spec-id>/
  mockup.py verify <spec-id>    exit non-zero if approval is missing or stale
  mockup.py status              show every mockup and its approval state
"""
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
MOCKUP_ROOT = os.path.join(REPO_ROOT, "docs", "mockups")
APPROVAL_FILE = "approval.json"

# Files whose content the reviewer actually saw. A change to any of them invalidates approval.
MOCKUP_EXTENSIONS = {".html", ".css", ".svg", ".png", ".jpg", ".jpeg", ".webp", ".md"}

# Token sources, if the project has them. Changing a colour after approval changes what was approved.
TOKEN_CANDIDATES = [
    "docs/mockups/_foundations/tokens.css",
    "docs/mockups/_foundations/tokens.json",
]


def git(*args, default=""):
    try:
        out = subprocess.run(["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, timeout=10)
        return out.stdout.strip() if out.returncode == 0 else default
    except Exception:
        return default


def hash_files(paths):
    """Order-independent, content-addressed. Path is included so a rename counts as a change."""
    digest = hashlib.sha256()
    for path in sorted(paths):
        rel = os.path.relpath(path, REPO_ROOT)
        digest.update(rel.encode())
        try:
            with open(path, "rb") as fh:
                for chunk in iter(lambda: fh.read(65536), b""):
                    digest.update(chunk)
        except Exception:
            digest.update(b"<unreadable>")
    return digest.hexdigest()


def mockup_files(spec_id):
    directory = os.path.join(MOCKUP_ROOT, spec_id)
    if not os.path.isdir(directory):
        return None, []
    found = []
    for root, dirs, files in os.walk(directory):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for name in files:
            if name == APPROVAL_FILE:
                continue  # the record must not hash itself
            if os.path.splitext(name)[1].lower() in MOCKUP_EXTENSIONS:
                found.append(os.path.join(root, name))
    return directory, sorted(found)


def token_files():
    return [os.path.join(REPO_ROOT, p) for p in TOKEN_CANDIDATES
            if os.path.exists(os.path.join(REPO_ROOT, p))]


def signature(spec_id):
    directory, files = mockup_files(spec_id)
    if directory is None:
        return None
    return {
        "artifacts": hash_files(files),
        "tokens": hash_files(token_files()) if token_files() else None,
        "fileCount": len(files),
    }


def approve(spec_id):
    directory, files = mockup_files(spec_id)
    if directory is None:
        print("No mockup at docs/mockups/%s/" % spec_id, file=sys.stderr)
        return 1
    if not files:
        print("docs/mockups/%s/ has no reviewable files." % spec_id, file=sys.stderr)
        return 1

    sig = signature(spec_id)
    record = {
        "specId": spec_id,
        "approvedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "commit": git("rev-parse", "HEAD", default="uncommitted"),
        "signature": sig,
        "files": [os.path.relpath(f, REPO_ROOT) for f in files],
        "_note": (
            "Approval is bound to the content hashed above. Editing any mockup file, or the design "
            "tokens they were rendered against, voids this approval. Do not edit this file by hand."
        ),
    }
    with open(os.path.join(directory, APPROVAL_FILE), "w") as fh:
        json.dump(record, fh, indent=2)
        fh.write("\n")
    print("Approved %s — %d files, signature %s" % (spec_id, len(files), sig["artifacts"][:12]))
    return 0


def verify(spec_id, quiet=False):
    directory, files = mockup_files(spec_id)
    if directory is None:
        if not quiet:
            print("MISSING   %s — no mockup directory" % spec_id)
        return 1

    path = os.path.join(directory, APPROVAL_FILE)
    if not os.path.exists(path):
        if not quiet:
            print("UNAPPROVED %s — no approval on record" % spec_id)
        return 1

    try:
        with open(path) as fh:
            record = json.load(fh)
    except Exception:
        if not quiet:
            print("CORRUPT   %s — approval file is unreadable" % spec_id)
        return 1

    current = signature(spec_id)
    recorded = record.get("signature") or {}

    if current["artifacts"] != recorded.get("artifacts"):
        if not quiet:
            print("STALE     %s — mockup changed since approval on %s"
                  % (spec_id, record.get("approvedAt", "?")))
            print("          Approval is void. Re-review, then run: mockup.py approve %s" % spec_id)
        return 1

    if recorded.get("tokens") is not None and current["tokens"] != recorded.get("tokens"):
        if not quiet:
            print("STALE     %s — design tokens changed since approval" % spec_id)
            print("          What was approved no longer renders the same way. Re-review.")
        return 1

    if not quiet:
        print("APPROVED  %s — %s, %d files"
              % (spec_id, record.get("approvedAt", "?"), recorded.get("fileCount", 0)))
    return 0


def status():
    if not os.path.isdir(MOCKUP_ROOT):
        print("No mockups yet.")
        return 0
    ids = sorted(d for d in os.listdir(MOCKUP_ROOT)
                 if os.path.isdir(os.path.join(MOCKUP_ROOT, d)) and not d.startswith("_"))
    if not ids:
        print("No mockups yet.")
        return 0
    failures = 0
    for spec_id in ids:
        failures += 1 if verify(spec_id) else 0
    print("\n%d mockups, %d approved, %d needing attention"
          % (len(ids), len(ids) - failures, failures))
    return 0


def main():
    if len(sys.argv) < 2:
        print(__doc__.strip())
        return 2
    command = sys.argv[1]
    if command == "status":
        return status()
    if command in ("approve", "verify"):
        if len(sys.argv) < 3:
            print("Usage: mockup.py %s <spec-id>" % command, file=sys.stderr)
            return 2
        return approve(sys.argv[2]) if command == "approve" else verify(sys.argv[2])
    print("Unknown command: %s" % command, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
